version: "3.8"
services:
  db:
    build: ./db
    environment:
      MYSQL_ROOT_PASSWORD: ""
      MYSQL_DATABASE: github-node
    restart: always
  web:
    build: ./github-auth-node
    environment:
      MYSQL_DATABASE: github-node
      MYSQL_USER: root
      MYSQL_PASSWORD: ""
      MYSQL_HOST: 127.0.0.1
    ports:
      - "9000:9000"
    depends_on:
      - db
    restart: on-failure